In [1]:
import numpy as np

In [24]:
arr = np.array((2,4,5,6,7,8))
arr[0]
print(arr)

[2 4 5 6 7 8]


In [25]:
arr = np.arange(0,260,24)
arr

array([  0,  24,  48,  72,  96, 120, 144, 168, 192, 216, 240])

In [26]:
arr = np.zeros([2,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr= np.ones([3,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Creating array from file

In [32]:
data = np.loadtxt("../data/example1.txt",dtype=int)
data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
data = np.loadtxt("../data/example2.txt",skiprows=2,usecols=1,dtype=str)
data
for val in data:
    print(val)

Scott
Eric
John
Sara


In [44]:
data = np.loadtxt("../data/example3.txt",skiprows=2,usecols=1,dtype=str,delimiter=',')
print(data)
for val in data:
    print(val)

['Scott' 'Eric' 'John' 'Sara']
Scott
Eric
John
Sara


In [45]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print("Array shape is:",x.shape)
print("Array data type is: ",x.dtype)
print("Array dimensions:",x.ndim)
print("Array size:",x.size)
print("Array itemsize:",x.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array shape is: (3, 3)
Array data type is:  int64
Array dimensions: 2
Array size: 9
Array itemsize: 8


In [47]:
x = np.ones([2,4,5])
print(x)
print('dimension',x.ndim)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
dimension 3


In [48]:
a = np.array([2,5,7,35,46])
print(a[-1])
print(a[2:5])

46
[ 7 35 46]


In [57]:
arr = np.arange(1,10)
reshape_arr = arr.reshape((3,3))
print(reshape_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
