
##Reshaping Arrays


In [1]:
import numpy as np

In [5]:
arr = np.arange(1,13)
reshape_arr = arr.reshape(4,3)
reshape_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
arr1 = np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
reshape_arr = arr1.reshape(-1)
reshape_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
arr1 = np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
reshape_arr = arr1.flatten()
reshape_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#Joining and Splitting Arrays

In [11]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])
arr1 =  np.concatenate((a,b))
arr2 = np.concatenate((a,b),axis=1)
arr1,arr2

(array([[1, 2],
        [3, 4],
        [4, 5],
        [6, 7]]),
 array([[1, 2, 4, 5],
        [3, 4, 6, 7]]))

In [14]:
a = np.array([[1,2,5],[3,4,6],[6,8,9]])
b = np.array([[5,6,8],[7,8,8],[3,6,8]])
c = np.array([[5,6,8],[7,8,8],[3,6,8]])

print ('Stack the two arrays along axis 0:') 
print (np.stack((a,b,c),0))

print ('Stack the two arrays along axis 1:')
print (np.stack((a,b,c),1))

Stack the two arrays along axis 0:
[[[1 2 5]
  [3 4 6]
  [6 8 9]]

 [[5 6 8]
  [7 8 8]
  [3 6 8]]

 [[5 6 8]
  [7 8 8]
  [3 6 8]]]
Stack the two arrays along axis 1:
[[[1 2 5]
  [5 6 8]
  [5 6 8]]

 [[3 4 6]
  [7 8 8]
  [7 8 8]]

 [[6 8 9]
  [3 6 8]
  [3 6 8]]]


In [18]:
a = np.array([[1,2,5],[3,4,6],[6,8,9]])
b = np.array([[5,6,8],[7,8,8],[3,6,8]])
c = np.array([[5,6,8],[7,8,8],[3,6,8]])
print (np.hstack((a,b,c)))
print (np.vstack((a,b,c)))

[[1 2 5 5 6 8 5 6 8]
 [3 4 6 7 8 8 7 8 8]
 [6 8 9 3 6 8 3 6 8]]
[[1 2 5]
 [3 4 6]
 [6 8 9]
 [5 6 8]
 [7 8 8]
 [3 6 8]
 [5 6 8]
 [7 8 8]
 [3 6 8]]


In [24]:

arr = np.array([1, 2, 3, 4, 5, 6])
split_array = np.array_split(arr,4)
split_array


[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6],[5, 6, 7]])
split_array = np.array_split(arr,3)
split_array

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[5, 6, 7]])]

In [35]:
arr3 = np.array([[[1,2, 5],
  [3 ,4, 6],
  [6 ,8, 9]],

 [[5, 6, 8],
  [7 ,8, 8],
  [3 ,6, 8]],

 [[5 ,6, 8],
  [7 ,8, 8],
  [3 ,6, 8]],

[[1,2, 5],
  [3 ,4, 6],
  [6 ,8, 9]],

 [[5, 6, 8],
  [7 ,8, 8],
  [3 ,6, 8]],

 [[5 ,6, 8],
  [7 ,8, 8],
  [3 ,6, 8]]])

split_array = np.array_split(arr3,2)
split_array

[array([[[1, 2, 5],
         [3, 4, 6],
         [6, 8, 9]],
 
        [[5, 6, 8],
         [7, 8, 8],
         [3, 6, 8]],
 
        [[5, 6, 8],
         [7, 8, 8],
         [3, 6, 8]]]),
 array([[[1, 2, 5],
         [3, 4, 6],
         [6, 8, 9]],
 
        [[5, 6, 8],
         [7, 8, 8],
         [3, 6, 8]],
 
        [[5, 6, 8],
         [7, 8, 8],
         [3, 6, 8]]])]

In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6],[5, 6, 7]])
split_array = np.array_split(arr,3,axis=1)
split_array

[array([[1],
        [4],
        [5]]),
 array([[2],
        [5],
        [6]]),
 array([[3],
        [6],
        [7]])]

In [40]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
split_h = np.hsplit(arr,3)
split_v = np.vsplit(arr,3)
split_h,split_v

([array([[ 1],
         [ 4],
         [ 7],
         [10],
         [13],
         [16]]),
  array([[ 2],
         [ 5],
         [ 8],
         [11],
         [14],
         [17]]),
  array([[ 3],
         [ 6],
         [ 9],
         [12],
         [15],
         [18]])],
 [array([[1, 2, 3],
         [4, 5, 6]]),
  array([[ 7,  8,  9],
         [10, 11, 12]]),
  array([[13, 14, 15],
         [16, 17, 18]])])

In [41]:
## changing the type of the array

In [43]:
arr =  np.array([1.1, 2.1, 3.1])
changedarray_dt = arr.astype('i')
changedarray_dt

array([1, 2, 3], dtype=int32)

In [45]:
arr =  np.array([1, 2, 3])
changedarray_dt = arr.astype(bool)
changedarray_float = arr.astype('f')
changedarray_dt, changedarray_float

(array([ True,  True,  True]), array([1., 2., 3.], dtype=float32))

##Sorting and Searching Arrays

In [50]:
array = np.array([10, 2, 9, -1])
arr1 = np.array([True, False, True])
arr2 = np.array(['banana', 'cherry', 'apple'])
sorted_array1 = np.sort(array)
sorted_array2 = np.sort(arr1)
sorted_array3 = np.sort(arr2)
sorted_array1,sorted_array2,sorted_array3

(array([-1,  2,  9, 10]),
 array([False,  True,  True]),
 array(['apple', 'banana', 'cherry'], dtype='<U6'))

In [52]:
array = np.array([10, 2, 9, -1])
sorted_array1 = np.argsort(array)
new_array = array[sorted_array1]
new_array

array([-1,  2,  9, 10])

In [53]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
index  = np.where(arr == 4)
index

(array([3, 5, 6]),)

In [55]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
index_even = np.where(arr%2 == 0)
index_odd = np.where(arr%2 == 1)
index_even, index_odd

((array([1, 3, 5, 6]),), (array([0, 2, 4]),))

In [58]:
## Search From the Right Side
## By default the left most index is returned, but we can give side='right' to return the right most index instead

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')
y = np.searchsorted(arr, 7)
z = np.searchsorted(arr, [8,4,6])
print(y)
print(z)
print(x)

1
[2 0 0]
2
