In [1]:
import numpy as np

In [2]:
x = np.zeros(4,dtype=int)
x

array([0, 0, 0, 0])

In [5]:
data = np.zeros(4, dtype={ 'names' :('name','age','weight'),
                             'formats' :('U10','i4','f8') })
print(data.dtype)
data

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [6]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [7]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [8]:
data[0]

('Alice', 25, 55.)

In [14]:
data[-3]['name']

'Bob'

In [15]:
data[data['age']>30]['name']

array(['Bob', 'Cathy'], dtype='<U10')

In [19]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [20]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_,10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [21]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [33]:
import numpy as np

tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
import numpy as np

# Define a structured dtype with fields 'name', 'age', and 'weight'
tp = np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f4')])

# Create a structured array
data = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)], dtype=tp)
print(data['age'])
# View the structured array as a record array
data_rec = data.view(np.recarray)
data_rec1 = data.view()
# Access the 'age' field as an attribute
print(data_rec.weight)
print(data_rec1['weight'])  
print(data_rec1.weight) 
## It will not support , to support the written syntax we need to use np.recarray (so that we can use dot notation to access fields)
print(data_rec['weight'])

[25 30]
[55.  85.5]
[55.  85.5]


AttributeError: 'numpy.ndarray' object has no attribute 'weight'

In [40]:
%timeit data['age']
%timeit data_rec.weight
%timeit data_rec['weight']

40.9 ns ± 1.77 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
1.09 µs ± 20.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
623 ns ± 19.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
